### ISSUE TITLE
Compatible with Hogfather?

### ISSUE THREAD

**Issue by asheenlevrai** [issmirnov/dokuwiki-plugin-widearea#1]
Hi :)

I noticed that the plugin is compatible with Greebo (apparently it works).
Before I update Dokuwiki, I was wondering if the plugin is compatible with Hogfather?

Thank you very much in advance for your help.
Best,
-a-

**Comment by issmirnov** [comment]
Hey, just tested on Release 2020-07-29 "Hogfather" and it seems to be working fine:

<img width="940" alt="Screen Shot 2021-04-13 at 5 27 17 PM" src="https://user-images.githubusercontent.com/5771615/114637169-8fa91500-9c7d-11eb-99c1-8599e245d29c.png">

<img width="940" alt="Screen Shot 2021-04-13 at 5 27 09 PM" src="https://user-images.githubusercontent.com/5771615/114637167-8f107e80-9c7d-11eb-985c-23a8d1d28f0f.png">

**Comment by asheenlevrai** [comment]
Thanks a lot :D
